{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '.header-search-button')).click\n\nReason: ElementNotInteractableException: Message: element not interactable\n  (Session info: headless chrome=114.0.5735.198)\nStacktrace:\n#0 0x556a2ab0b4e3 <unknown>\n#1 0x556a2a83ab00 <unknown>\n#2 0x556a2a877fa1 <unknown>\n#3 0x556a2a86d1da <unknown>\n#4 0x556a2a896012 <unknown>\n#5 0x556a2a86cb03 <unknown>\n#6 0x556a2a8961de <unknown>\n#7 0x556a2a8ae30e <unknown>\n#8 0x556a2a895de3 <unknown>\n#9 0x556a2a86b2dd <unknown>\n#10 0x556a2a86c34e <unknown>\n#11 0x556a2aacb3e4 <unknown>\n#12 0x556a2aacf3d7 <unknown>\n#13 0x556a2aad9b20 <unknown>\n#14 0x556a2aad0023 <unknown>\n#15 0x556a2aa9e1aa <unknown>\n#16 0x556a2aaf46b8 <unknown>\n#17 0x556a2aaf4847 <unknown>\n#18 0x556a2ab04243 <unknown>\n#19 0x7fcb7c513b43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1688895690186/1688895690186.png\nPageSource: file:///home/runner/.selene/screenshots/1688895690186/1688895690186.html","children":[{"name":"test_decorator_steps","uid":"ff1e2935ef289720","parentUid":"e8e1fadd38dff0f4882f4a4d23fbcb2d","status":"failed","time":{"start":1688895698375,"stop":1688895704919,"duration":6544},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"e8e1fadd38dff0f4882f4a4d23fbcb2d"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"},{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53727): Max retries exceeded with url: /session/2a5fb67aa6ec8d61141542601b855b41/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feff28be590>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_github","uid":"147c37543aec9a4b","parentUid":"3916686b18df60618dbf46e841639e80","status":"broken","time":{"start":1688895705067,"stop":1688895705067,"duration":0},"flaky":true,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"3916686b18df60618dbf46e841639e80"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53727): Max retries exceeded with url: /session/2a5fb67aa6ec8d61141542601b855b41/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feff1164b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_dynamic_steps","uid":"6aa308b9f3fb36c4","parentUid":"1aadd46b14c5ca1a3dc7f88c7fc8914f","status":"broken","time":{"start":1688895705226,"stop":1688895705226,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"1aadd46b14c5ca1a3dc7f88c7fc8914f"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}